# Generated by Django 5.0.4 on 2024-04-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignedapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='register',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
